# Generated by Django 2.1 on 2019-03-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190318_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.TextField(max_length=1000),
        ),
    ]
